# Generated by Django 3.0.6 on 2020-06-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200620_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, help_text='additional information', verbose_name='message'),
        ),
    ]
