# Generated by Django 3.0.6 on 2020-05-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200522_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRequest',
            new_name='Order',
        ),
    ]
