# Generated by Django 3.0.6 on 2020-06-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_from',
            field=models.CharField(default='pikk 1', max_length=128, verbose_name='address from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_to',
            field=models.CharField(default='roosikransi 34', max_length=128, verbose_name='address to'),
            preserve_default=False,
        ),
    ]
