# Generated by Django 3.0.6 on 2020-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200702_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='movers_num',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, verbose_name='number of required movers'),
        ),
    ]
