# Generated by Django 3.0.6 on 2020-06-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200621_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(default='2020-06-22 01:21'),
            preserve_default=False,
        ),
    ]
