# Generated by Django 3.0.6 on 2020-07-05 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_movers_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='deliver_date',
            new_name='delivery_end',
        ),
        migrations.AddField(
            model_name='work',
            name='delivery_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
