# Generated by Django 3.0.6 on 2020-06-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_deliver_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(verbose_name='delivery date'),
        ),
    ]
