# Generated by Django 3.0.6 on 2020-06-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200621_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_date',
            new_name='delivery_date',
        ),
    ]
