# Generated by Django 3.0.6 on 2020-07-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200714_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
