# Generated by Django 3.0.6 on 2020-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_work_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='drivers_notified',
            field=models.BooleanField(default=False),
        ),
    ]
