# Generated by Django 3.0.6 on 2020-07-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_work_drivers_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='drivers_notified',
        ),
    ]
