# Generated by Django 3.0.6 on 2020-07-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_work_drivers_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drivers_notified',
            field=models.BooleanField(default=False),
        ),
    ]
