# Generated by Django 3.0.6 on 2020-07-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_drivers_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='order_confirmed',
            new_name='confirmed',
        ),
    ]
