# Generated by Django 3.0.6 on 2020-07-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200725_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='confirmed',
            new_name='order_confirmed',
        ),
    ]
