# Generated by Django 3.0.6 on 2020-08-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200725_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Cash')], default=1, verbose_name='payment method'),
        ),
    ]
