# Generated by Django 3.0.6 on 2020-08-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_free_drivers',
            field=models.BooleanField(default=False),
        ),
    ]
