# Generated by Django 3.0.6 on 2020-08-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_no_free_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='verification_code_sent',
            field=models.BooleanField(default=False),
        ),
    ]
