# Generated by Django 3.0.6 on 2020-08-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_verification_code_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_end',
            field=models.DateTimeField(verbose_name='delivery end'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_start',
            field=models.DateTimeField(verbose_name='delivery start'),
        ),
    ]
