# Generated by Django 3.0.6 on 2020-08-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200811_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='delivery_end',
            field=models.DateTimeField(verbose_name='delivery end'),
        ),
        migrations.AlterField(
            model_name='work',
            name='delivery_start',
            field=models.DateTimeField(verbose_name='delivery start'),
        ),
    ]
