# Generated by Django 3.0.6 on 2020-08-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200812_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='delivery_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='delivery_start',
            field=models.DateTimeField(),
        ),
    ]
