# Generated by Django 3.0.6 on 2020-08-13 20:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200812_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_from',
            field=models.CharField(help_text='Delivery start address', max_length=128, verbose_name='address from'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_to',
            field=models.CharField(help_text='Delivery end address', max_length=128, verbose_name='address to'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_end',
            field=models.DateTimeField(help_text='Delivery end time', verbose_name='delivery end'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_start',
            field=models.DateTimeField(help_text='Delivery start time', verbose_name='delivery start'),
        ),
        migrations.AlterField(
            model_name='order',
            name='movers_num',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0, help_text='Number of required movers', verbose_name='number of required movers'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone'),
        ),
    ]
