# Generated by Django 3.0.6 on 2020-09-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200813_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work',
        ),
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Order'),
        ),
    ]
