# Generated by Django 3.0.6 on 2020-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200926_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collecting_works',
            field=models.BooleanField(default=True),
        ),
    ]
