# Generated by Django 3.0.6 on 2020-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200927_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collecting_works',
            field=models.BooleanField(default=True),
        ),
    ]
