# Generated by Django 3.0.6 on 2020-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200927_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zopa',
            field=models.BooleanField(default=True),
        ),
    ]
