# Generated by Django 3.0.6 on 2020-09-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_order_zopa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zopa',
        ),
    ]
