# Generated by Django 3.0.6 on 2020-10-01 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201001_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verification_code',
            field=models.CharField(max_length=4, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Verification code'),
        ),
    ]
