# Generated by Django 3.0.6 on 2020-10-05 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201005_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verification_code',
            field=models.CharField(help_text='Verification code is sent to your email', max_length=4, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Verification code'),
        ),
    ]
