# Generated by Django 3.0.6 on 2020-10-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201005_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Cash')], default=0, verbose_name='payment method'),
        ),
    ]
