# Generated by Django 3.0.6 on 2020-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20201021_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Cash')], default=2, verbose_name='payment method'),
        ),
    ]
