# Generated by Django 3.0.6 on 2020-05-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('DR', 'Driver'), ('CU', 'Customer'), ('NO', 'None')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('ik', models.IntegerField(blank=True, null=True, verbose_name='isikukood')),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True)),
                ('car_model', models.CharField(max_length=50, verbose_name='car model')),
                ('car_carrying', models.IntegerField(blank=True, null=True, verbose_name='car carrying')),
                ('car_number', models.CharField(max_length=7, verbose_name='car number')),
                ('payment', models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Bank'), (3, 'Both')], null=True, verbose_name='payment method')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
