# Generated by Django 3.0.6 on 2020-06-19 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200619_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_carrying',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='car carrying (kg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Cash')], default=1, verbose_name='payment method'),
        ),
    ]
