# Generated by Django 3.0.6 on 2020-10-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200927_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Russian'), (3, 'Estonian')], default=1, verbose_name='Preferred language'),
        ),
    ]
