# Generated by Django 3.0.6 on 2020-10-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Russian'), (3, 'Estonian')], default=1, help_text='Preferred language to use delivery24', verbose_name='Preferred language'),
        ),
    ]
