# Generated by Django 3.0.6 on 2020-10-22 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201005_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_type',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='car type'),
        ),
    ]
