# Generated by Django 3.0.6 on 2020-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L')], default=3, verbose_name='car type'),
        ),
    ]
