# Generated by Django 3.0.6 on 2020-10-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201022_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Cash')], default=0, verbose_name='payment method'),
        ),
    ]
