# Generated by Django 3.0.6 on 2020-06-18 00:24

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200618_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(7), core.utils.car_number_validator], verbose_name='car number'),
        ),
    ]
