# Generated by Django 3.0.6 on 2020-10-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201022_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='car_type',
            field=models.IntegerField(choices=[(0, 'S'), (1, 'M'), (2, 'L')], default=3, verbose_name='car type'),
        ),
    ]
